plugins {
    id("org.jetbrains.kotlinx.kover")
}

kover {
    reports {
        filters {
            excludes {
                // Generated bytecode nothing writes by hand, so counting it only depresses the
                // number without naming anything a test could cover.
                classes(
                    "*_Factory",
                    "*_HiltModules*",
                    "*_MembersInjector",
                    "*Hilt_*",
                    "*.ComposableSingletons*",
                    "*.databinding.*",
                    "*.BuildConfig",
                    "*_Impl",
                )
                annotatedBy("androidx.compose.ui.tooling.preview.Preview")
            }
        }
    }
}
